# Generated by Django 3.1.1 on 2020-10-12 22:38

from django.db import migrations, models
import stocktrader.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=stocktrader.storage.OverwriteStorage(), upload_to='uploaded/images')),
            ],
        ),
    ]
